
/**************************************************************
 *	
 *	song, 8 bit, 44100Hz,
 *	1 channel, 5930496 bytes/channel
 *	Total Size: 1 * 5930496 + 4 (header) = 5930540 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\GBA\Projects\Final Project\song.wav
 *	Time-stamp: Fri Mar 28 00:48:46 2014
 *	
 **************************************************************/

#ifndef __SONGH__
#define __SONGH__

#define SONGFREQ 44100
#define SONGLEN 5930496

extern const unsigned char song[5930496];

#endif /* __SONGH__ */
