
/**************************************************************
 *	
 *	entangledSong, 8 bit, 11025Hz,
 *	1 channel, 3153150 bytes/channel
 *	Total Size: 1 * 3153150 + 4 (header) = 3153194 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Zach\SkyDrive\Documents\Georgia Tech\Spring 2014\CS 2261\GBA\Projects\Final Project\assets\music\entangledSong.wav
 *	Time-stamp: Fri Apr 25 07:04:17 2014
 *	
 **************************************************************/

#ifndef __ENTANGLEDSONGH__
#define __ENTANGLEDSONGH__

#define ENTANGLEDSONGFREQ 11025
#define ENTANGLEDSONGLEN 3153150

extern const unsigned char entangledSong[3153150];

#endif /* __ENTANGLEDSONGH__ */
