
/**************************************************************
 *	
 *	gameSong, 8 bit, 11025Hz,
 *	1 channel, 1769512 bytes/channel
 *	Total Size: 1 * 1769512 + 4 (header) = 1769556 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Zach\SkyDrive\Documents\Georgia Tech\Spring 2014\CS 2261\GBA\Projects\Final Project\assets\music\gameSong.wav
 *	Time-stamp: Fri Apr 25 07:04:20 2014
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 1769512

extern const unsigned char gameSong[1769512];

#endif /* __GAMESONGH__ */
