
/**************************************************************
 *	
 *	loseSong, 8 bit, 11025Hz,
 *	1 channel, 2234567 bytes/channel
 *	Total Size: 1 * 2234567 + 4 (header) = 2234611 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Zach\SkyDrive\Documents\Georgia Tech\Spring 2014\CS 2261\GBA\Projects\Final Project\assets\music\loseSong.wav
 *	Time-stamp: Fri Apr 25 07:04:24 2014
 *	
 **************************************************************/

#ifndef __LOSESONGH__
#define __LOSESONGH__

#define LOSESONGFREQ 11025
#define LOSESONGLEN 2234567

extern const unsigned char loseSong[2234567];

#endif /* __LOSESONGH__ */
