
/**************************************************************
 *	
 *	menuSong, 8 bit, 11025Hz,
 *	1 channel, 2078042 bytes/channel
 *	Total Size: 1 * 2078042 + 4 (header) = 2078086 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Zach\SkyDrive\Documents\Georgia Tech\Spring 2014\CS 2261\GBA\Projects\Final Project\assets\music\menuSong.wav
 *	Time-stamp: Fri Apr 25 07:04:26 2014
 *	
 **************************************************************/

#ifndef __MENUSONGH__
#define __MENUSONGH__

#define MENUSONGFREQ 11025
#define MENUSONGLEN 2078042

extern const unsigned char menuSong[2078042];

#endif /* __MENUSONGH__ */
