
/**************************************************************
 *	
 *	winSong, 8 bit, 11025Hz,
 *	1 channel, 2844450 bytes/channel
 *	Total Size: 1 * 2844450 + 4 (header) = 2844494 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Zach\SkyDrive\Documents\Georgia Tech\Spring 2014\CS 2261\GBA\Projects\Final Project\assets\music\winSong.wav
 *	Time-stamp: Fri Apr 25 07:04:32 2014
 *	
 **************************************************************/

#ifndef __WINSONGH__
#define __WINSONGH__

#define WINSONGFREQ 11025
#define WINSONGLEN 2844450

extern const unsigned char winSong[2844450];

#endif /* __WINSONGH__ */
