
/**************************************************************
 *	
 *	jump, 8 bit, 11025Hz,
 *	1 channel, 3168 bytes/channel
 *	Total Size: 1 * 3168 + 4 (header) = 3212 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\GBA\Projects\Final Project\assets\sound\jump.wav
 *	Time-stamp: Tue Apr 22 23:15:52 2014
 *	
 **************************************************************/

#ifndef __JUMPH__
#define __JUMPH__

#define JUMPFREQ 11025
#define JUMPLEN 3168

extern const unsigned char jump[3168];

#endif /* __JUMPH__ */
