
/**************************************************************
 *	
 *	shift, 8 bit, 11025Hz,
 *	1 channel, 6336 bytes/channel
 *	Total Size: 1 * 6336 + 4 (header) = 6380 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\GBA\Projects\Final Project\assets\sound\shift.wav
 *	Time-stamp: Tue Apr 22 23:16:17 2014
 *	
 **************************************************************/

#ifndef __SHIFTH__
#define __SHIFTH__

#define SHIFTFREQ 11025
#define SHIFTLEN 6336

extern const unsigned char shift[6336];

#endif /* __SHIFTH__ */
